name: Terraform Build and Deploy on Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Allow GitHub to request an ID token

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Terraform (this will install Terraform)
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      # Step 3: Log in to Azure using Service Principal credentials
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 4: Terraform Initialization
      - name: Terraform Init
        run: terraform init

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Step 6: Terraform Apply (use --auto-approve to skip manual approval)
      - name: Terraform Apply
        run: terraform apply -auto-approve

      # Optional: Step to show Terraform Output (if applicable)
      - name: Show Terraform Output
        run: terraform output
